
name: trivy-keycloak

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read           # for actions/checkout to fetch code
      security-events: write   # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read            # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }} 

      - name: Pull Keycloak image
        run: |
          docker pull ghcr.io/cytrix-italia/keycloak/keycloak-keycloak:latest

      - name: Run Trivy vulnerability scanner Keycloak
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: 'ghcr.io/cytrix-italia/keycloak/keycloak-keycloak:latest'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results-keycloak.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          timeout: 30m

      - name: Upload Trivy scan results Keycloak
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-keycloak.sarif'
          category: 'trivy-keycloak'
